# api-receitas-vo-node


# compose syntax version.
version: "3.6"

# services declaration.
services:
  # MySQL
  mysql:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=api-receitas-vo-node
      - MYSQL_USER=api-receitas-vo-node
      - MYSQL_PASSWORD=api-receitas-vo-node
      - MYSQL_DATABASE=api-receitas-vo-node
    ports:
      - target: 3306
        published: 3306

# volumes declaration.
volumes:
  # mysql-data
  mysql-data:
    driver: local
